name: 'Get AVD arch'
description: 'Get the AVD architecture based on its API level.'
inputs:
    api-level:
        required: true
outputs:
    arch:
        value: ${{ steps.get-avd-arch.outputs.arch }}
runs:
    using: "composite"
    steps:
        - id: get-avd-arch
          run: echo "arch=$(if [ ${{ inputs.api-level }} -ge 30 ]; then echo x86_64; else echo x86; fi)" >> $GITHUB_OUTPUT
          shell: bash